github secret test 2

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -22,8 +22,12 @@ jobs:
           ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
           TEST: test
         run: |
-          echo "ETH_RPC_URL: $ETH_RPC_URL"
-          echo "TEST: $TEST"
+          if [ -z "$ETH_RPC_URL" ]; then
+            echo "Error: ETH_RPC_URL is not set"
+            exit 1
+          fi
+          echo ETH_RPC_URL: "$ETH_RPC_URL"
+          echo TEST: "$TEST"
           docker build -t e2e -f Dockerfile.e2e . --build-arg ETH_RPC_URL="$ETH_RPC_URL"
 
       - name: Run E2E Test
